#! /bin/bash
set -euo pipefail

read -p "Are you sure you want to execute the home server installation script on this machine? [y/N]: " -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Starting server setup"
    bash ./subscripts/install-docker

fi
